<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Mahasiswa;
use App\Models\User;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pingkyUser = User::where('nim_nip', '2271020052')->first();

        $students = [
            // Angkatan 2022
            [
                'nim' => '2271020052',
                'nama' => 'Pingky Hera Veliyanti',
                'angkatan' => 2022,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SPAN-PTKIN',
                'email' => 'pingky@student.uinril.ac.id',
                'no_hp' => '089876543210',
                'alamat' => 'Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => $pingkyUser?->id,
            ],
            [
                'nim' => '2271020001',
                'nama' => 'Ahmad Rian Pratama',
                'angkatan' => 2022,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'SNBP',
                'email' => 'ahmad.rian@student.uinril.ac.id',
                'no_hp' => '081234500001',
                'alamat' => 'Sukarame, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020002',
                'nama' => 'Budi Santoso',
                'angkatan' => 2022,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'UM-PTKIN',
                'email' => 'budi.santoso@student.uinril.ac.id',
                'no_hp' => '081234500002',
                'alamat' => 'Kedaton, Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020003',
                'nama' => 'Citra Dewi Lestari',
                'angkatan' => 2022,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SNBT',
                'email' => 'citra.dewi@student.uinril.ac.id',
                'no_hp' => '081234500003',
                'alamat' => 'Way Halim, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020004',
                'nama' => 'Dimas Arya Putra',
                'angkatan' => 2022,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'Mandiri',
                'email' => 'dimas.arya@student.uinril.ac.id',
                'no_hp' => '081234500004',
                'alamat' => 'Natar, Lampung Selatan',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020005',
                'nama' => 'Eka Putri Rahayu',
                'angkatan' => 2022,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SPAN-PTKIN',
                'email' => 'eka.putri@student.uinril.ac.id',
                'no_hp' => '081234500005',
                'alamat' => 'Kemiling, Bandar Lampung',
                'tinggal_dengan' => 'Saudara',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020006',
                'nama' => 'Fajar Hidayatullah',
                'angkatan' => 2022,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'UM-PTKIN',
                'email' => 'fajar.h@student.uinril.ac.id',
                'no_hp' => '081234500006',
                'alamat' => 'Tanjung Karang, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020007',
                'nama' => 'Gita Nurul Aini',
                'angkatan' => 2022,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SNBP',
                'email' => 'gita.nurul@student.uinril.ac.id',
                'no_hp' => '081234500007',
                'alamat' => 'Rajabasa, Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020008',
                'nama' => 'Hendra Setiawan',
                'angkatan' => 2022,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'Mandiri',
                'email' => 'hendra.s@student.uinril.ac.id',
                'no_hp' => '081234500008',
                'alamat' => 'Jati Agung, Lampung Selatan',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020009',
                'nama' => 'Indah Permatasari',
                'angkatan' => 2022,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SPAN-PTKIN',
                'email' => 'indah.p@student.uinril.ac.id',
                'no_hp' => '081234500009',
                'alamat' => 'Teluk Betung, Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2271020010',
                'nama' => 'Joko Tri Wahyudi',
                'angkatan' => 2022,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'UM-PTKIN',
                'email' => 'joko.tri@student.uinril.ac.id',
                'no_hp' => '081234500010',
                'alamat' => 'Panjang, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],

            // Angkatan 2021
            [
                'nim' => '2171020001',
                'nama' => 'Kevin Alamsyah',
                'angkatan' => 2021,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'SNBP',
                'email' => 'kevin.alam@student.uinril.ac.id',
                'no_hp' => '081234500011',
                'alamat' => 'Sukarame, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020002',
                'nama' => 'Lestari Ayu Wulandari',
                'angkatan' => 2021,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SPAN-PTKIN',
                'email' => 'lestari.ayu@student.uinril.ac.id',
                'no_hp' => '081234500012',
                'alamat' => 'Gedong Meneng, Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020003',
                'nama' => 'Muhammad Farhan',
                'angkatan' => 2021,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'SNBT',
                'email' => 'm.farhan@student.uinril.ac.id',
                'no_hp' => '081234500013',
                'alamat' => 'Way Kandis, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020004',
                'nama' => 'Nadia Salsabila',
                'angkatan' => 2021,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'UM-PTKIN',
                'email' => 'nadia.salsa@student.uinril.ac.id',
                'no_hp' => '081234500014',
                'alamat' => 'Kedaton, Bandar Lampung',
                'tinggal_dengan' => 'Saudara',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020005',
                'nama' => 'Oki Prasetyo',
                'angkatan' => 2021,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'Mandiri',
                'email' => 'oki.prasetyo@student.uinril.ac.id',
                'no_hp' => '081234500015',
                'alamat' => 'Labuhan Ratu, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Cuti',
                'user_id' => null,
            ],
            [
                'nim' => '2171020006',
                'nama' => 'Putri Melati',
                'angkatan' => 2021,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SPAN-PTKIN',
                'email' => 'putri.melati@student.uinril.ac.id',
                'no_hp' => '081234500016',
                'alamat' => 'Way Dadi, Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020007',
                'nama' => 'Rian Kurniawan',
                'angkatan' => 2021,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'UM-PTKIN',
                'email' => 'rian.k@student.uinril.ac.id',
                'no_hp' => '081234500017',
                'alamat' => 'Teluk Betung, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020008',
                'nama' => 'Siti Nurhaliza',
                'angkatan' => 2021,
                'jenis_kelamin' => 'P',
                'jalur_masuk' => 'SNBP',
                'email' => 'siti.nur@student.uinril.ac.id',
                'no_hp' => '081234500018',
                'alamat' => 'Pramuka, Bandar Lampung',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020009',
                'nama' => 'Teguh Wicaksono',
                'angkatan' => 2021,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'Mandiri',
                'email' => 'teguh.w@student.uinril.ac.id',
                'no_hp' => '081234500019',
                'alamat' => 'Kemiling, Bandar Lampung',
                'tinggal_dengan' => 'Kos',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
            [
                'nim' => '2171020010',
                'nama' => 'Wahyu Hidayat',
                'angkatan' => 2021,
                'jenis_kelamin' => 'L',
                'jalur_masuk' => 'UM-PTKIN',
                'email' => 'wahyu.h@student.uinril.ac.id',
                'no_hp' => '081234500020',
                'alamat' => 'Natar, Lampung Selatan',
                'tinggal_dengan' => 'Orang Tua',
                'status_mahasiswa' => 'Aktif',
                'user_id' => null,
            ],
        ];

        foreach ($students as $student) {
            Mahasiswa::updateOrCreate(
                ['nim' => $student['nim']],
                $student
            );
        }
    }
}
